parameters: {}
environment: {}
packages:
  - name: web
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: serve
        binary: false
        runtime: nodejs:18
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
# VITE_API_URL: ${VITE_API_URL}
# NODE_ENV: production
