packages:
  - name: portfolio-api
    actions:
      - name: sendmail
        runtime: nodejs:18
        environment: 
          SMTP_HOST: "${SMTP_HOST}"
          SMTP_PORT: "${SMTP_PORT}"
          SMTP_EMAIL: "${SMTP_EMAIL}"
          SMTP_PASS: "${SMTP_PASS}"
          # LOG_DESTINATIONS: '[{"datadog":{"endpoint":"https://http-intake.logs.datadoghq.com","api_key":"f8eb6cec4eae129da1408c8960d9ea40"}}]'

        