parameters: {}
environment: {}
packages:
  - name: sample
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: hello
        binary: false
        main: ""
        runtime: nodejs:default
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
      - name: serve
        binary: false
        runtime: nodejs:18
        web: true
        webSecure: false
        parameters: {}
        environment:
          VITE_API_URL: ${VITE_API_URL}
          NODE_ENV: ${NODE_ENV}
        annotations: {}
        limits: {}
